//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 06:11:41 PM IST 
//


package com.girmiti.nexo.acceptorcancellationadvice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardholderVerificationCapability4Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CardholderVerificationCapability4Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="APKI"/>
 *     &lt;enumeration value="CHDT"/>
 *     &lt;enumeration value="MNSG"/>
 *     &lt;enumeration value="MNVR"/>
 *     &lt;enumeration value="FBIG"/>
 *     &lt;enumeration value="FBIO"/>
 *     &lt;enumeration value="FDSG"/>
 *     &lt;enumeration value="FCPN"/>
 *     &lt;enumeration value="FEPN"/>
 *     &lt;enumeration value="NPIN"/>
 *     &lt;enumeration value="PKIS"/>
 *     &lt;enumeration value="SCEC"/>
 *     &lt;enumeration value="NBIO"/>
 *     &lt;enumeration value="NOVF"/>
 *     &lt;enumeration value="OTHR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CardholderVerificationCapability4Code")
@XmlEnum
public enum CardholderVerificationCapability4Code {

    APKI,
    CHDT,
    MNSG,
    MNVR,
    FBIG,
    FBIO,
    FDSG,
    FCPN,
    FEPN,
    NPIN,
    PKIS,
    SCEC,
    NBIO,
    NOVF,
    OTHR;

    public String value() {
        return name();
    }

    public static CardholderVerificationCapability4Code fromValue(String v) {
        return valueOf(v);
    }

}
