//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 06:11:41 PM IST 
//


package com.girmiti.nexo.acceptorcancellationadvice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PINFormat3Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PINFormat3Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ISO0"/>
 *     &lt;enumeration value="ISO1"/>
 *     &lt;enumeration value="ISO2"/>
 *     &lt;enumeration value="ISO3"/>
 *     &lt;enumeration value="ISO4"/>
 *     &lt;enumeration value="ISO5"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PINFormat3Code")
@XmlEnum
public enum PINFormat3Code {

    @XmlEnumValue("ISO0")
    ISO_0("ISO0"),
    @XmlEnumValue("ISO1")
    ISO_1("ISO1"),
    @XmlEnumValue("ISO2")
    ISO_2("ISO2"),
    @XmlEnumValue("ISO3")
    ISO_3("ISO3"),
    @XmlEnumValue("ISO4")
    ISO_4("ISO4"),
    @XmlEnumValue("ISO5")
    ISO_5("ISO5");
    private final String value;

    PINFormat3Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PINFormat3Code fromValue(String v) {
        for (PINFormat3Code c: PINFormat3Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
