//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.24 at 07:42:54 AM PDT 
//


package com.girmiti.nexo.acceptorcurrencyconversionrequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardPaymentServiceType3Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CardPaymentServiceType3Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IRES"/>
 *     &lt;enumeration value="URES"/>
 *     &lt;enumeration value="PRES"/>
 *     &lt;enumeration value="ARES"/>
 *     &lt;enumeration value="FREC"/>
 *     &lt;enumeration value="RREC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CardPaymentServiceType3Code")
@XmlEnum
public enum CardPaymentServiceType3Code {

    IRES,
    URES,
    PRES,
    ARES,
    FREC,
    RREC;

    public String value() {
        return name();
    }

    public static CardPaymentServiceType3Code fromValue(String v) {
        return valueOf(v);
    }

}
