//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.24 at 07:42:54 AM PDT 
//


package com.girmiti.nexo.acceptorcurrencyconversionrequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccptrCcyConvsReq" type="{urn:iso:std:iso:20022:tech:xsd:caaa.016.001.06}AcceptorCurrencyConversionRequestV06"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name="Document" , namespace="urn:iso:std:iso:20022:tech:xsd:caaa.016.001.06")
@XmlType(name = "Document", propOrder = {
    "accptrCcyConvsReq"
})
public class Document {

    @XmlElement(name = "AccptrCcyConvsReq", required = true, namespace="urn:iso:std:iso:20022:tech:xsd:caaa.016.001.06")
    protected AcceptorCurrencyConversionRequestV06 accptrCcyConvsReq;

    /**
     * Gets the value of the accptrCcyConvsReq property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptorCurrencyConversionRequestV06 }
     *     
     */    
    public AcceptorCurrencyConversionRequestV06 getAccptrCcyConvsReq() {
        return accptrCcyConvsReq;
    }

    /**
     * Sets the value of the accptrCcyConvsReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptorCurrencyConversionRequestV06 }
     *     
     */
    public void setAccptrCcyConvsReq(AcceptorCurrencyConversionRequestV06 value) {
        this.accptrCcyConvsReq = value;
    }

}
