//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.24 at 07:42:54 AM PDT 
//


package com.girmiti.nexo.acceptorcurrencyconversionrequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationCategory3Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LocationCategory3Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INDR"/>
 *     &lt;enumeration value="IPMP"/>
 *     &lt;enumeration value="MPOI"/>
 *     &lt;enumeration value="MPMP"/>
 *     &lt;enumeration value="MSLE"/>
 *     &lt;enumeration value="SSLE"/>
 *     &lt;enumeration value="VNDG"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LocationCategory3Code")
@XmlEnum
public enum LocationCategory3Code {

    INDR,
    IPMP,
    MPOI,
    MPMP,
    MSLE,
    SSLE,
    VNDG;

    public String value() {
        return name();
    }

    public static LocationCategory3Code fromValue(String v) {
        return valueOf(v);
    }

}
