//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.24 at 07:42:54 AM PDT 
//


package com.girmiti.nexo.acceptorcurrencyconversionrequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitOfMeasure6Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitOfMeasure6Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PIEC"/>
 *     &lt;enumeration value="TONS"/>
 *     &lt;enumeration value="FOOT"/>
 *     &lt;enumeration value="GBGA"/>
 *     &lt;enumeration value="USGA"/>
 *     &lt;enumeration value="GRAM"/>
 *     &lt;enumeration value="INCH"/>
 *     &lt;enumeration value="KILO"/>
 *     &lt;enumeration value="PUND"/>
 *     &lt;enumeration value="METR"/>
 *     &lt;enumeration value="CMET"/>
 *     &lt;enumeration value="MMET"/>
 *     &lt;enumeration value="LITR"/>
 *     &lt;enumeration value="CELI"/>
 *     &lt;enumeration value="MILI"/>
 *     &lt;enumeration value="GBOU"/>
 *     &lt;enumeration value="USOU"/>
 *     &lt;enumeration value="GBQA"/>
 *     &lt;enumeration value="USQA"/>
 *     &lt;enumeration value="GBPI"/>
 *     &lt;enumeration value="USPI"/>
 *     &lt;enumeration value="MILE"/>
 *     &lt;enumeration value="KMET"/>
 *     &lt;enumeration value="YARD"/>
 *     &lt;enumeration value="SQKI"/>
 *     &lt;enumeration value="HECT"/>
 *     &lt;enumeration value="ARES"/>
 *     &lt;enumeration value="SMET"/>
 *     &lt;enumeration value="SCMT"/>
 *     &lt;enumeration value="SMIL"/>
 *     &lt;enumeration value="SQMI"/>
 *     &lt;enumeration value="SQYA"/>
 *     &lt;enumeration value="SQFO"/>
 *     &lt;enumeration value="SQIN"/>
 *     &lt;enumeration value="ACRE"/>
 *     &lt;enumeration value="KWHO"/>
 *     &lt;enumeration value="DGEU"/>
 *     &lt;enumeration value="GGEU"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UnitOfMeasure6Code")
@XmlEnum
public enum UnitOfMeasure6Code {

    PIEC,
    TONS,
    FOOT,
    GBGA,
    USGA,
    GRAM,
    INCH,
    KILO,
    PUND,
    METR,
    CMET,
    MMET,
    LITR,
    CELI,
    MILI,
    GBOU,
    USOU,
    GBQA,
    USQA,
    GBPI,
    USPI,
    MILE,
    KMET,
    YARD,
    SQKI,
    HECT,
    ARES,
    SMET,
    SCMT,
    SMIL,
    SQMI,
    SQYA,
    SQFO,
    SQIN,
    ACRE,
    KWHO,
    DGEU,
    GGEU;

    public String value() {
        return name();
    }

    public static UnitOfMeasure6Code fromValue(String v) {
        return valueOf(v);
    }

}
