//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.26 at 12:10:24 PM IST 
//


package com.girmiti.nexo.acceptordiagnosticrequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeType1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AttributeType1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CNAT"/>
 *     &lt;enumeration value="LATT"/>
 *     &lt;enumeration value="OATT"/>
 *     &lt;enumeration value="OUAT"/>
 *     &lt;enumeration value="CATT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AttributeType1Code")
@XmlEnum
public enum AttributeType1Code {

    CNAT,
    LATT,
    OATT,
    OUAT,
    CATT;

    public String value() {
        return name();
    }

    public static AttributeType1Code fromValue(String v) {
        return valueOf(v);
    }

}
