//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 06:16:22 PM IST 
//


package com.girmiti.nexo.acceptorcancellationresponse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.girmiti.nexo.AcceptorCancellationRes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:caaa.006.001.07", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.girmiti.nexo.AcceptorCancellationRes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link KEK5 }
     * 
     */
    public KEK5 createKEK5() {
        return new KEK5();
    }

    /**
     * Create an instance of {@link CertificateIssuer1 }
     * 
     */
    public CertificateIssuer1 createCertificateIssuer1() {
        return new CertificateIssuer1();
    }

    /**
     * Create an instance of {@link PlainCardData15 }
     * 
     */
    public PlainCardData15 createPlainCardData15() {
        return new PlainCardData15();
    }

    /**
     * Create an instance of {@link GenericIdentification53 }
     * 
     */
    public GenericIdentification53 createGenericIdentification53() {
        return new GenericIdentification53();
    }

    /**
     * Create an instance of {@link CardPaymentTransactionDetails35 }
     * 
     */
    public CardPaymentTransactionDetails35 createCardPaymentTransactionDetails35() {
        return new CardPaymentTransactionDetails35();
    }

    /**
     * Create an instance of {@link KeyTransport5 }
     * 
     */
    public KeyTransport5 createKeyTransport5() {
        return new KeyTransport5();
    }

    /**
     * Create an instance of {@link AuthenticatedData5 }
     * 
     */
    public AuthenticatedData5 createAuthenticatedData5() {
        return new AuthenticatedData5();
    }

    /**
     * Create an instance of {@link CardPaymentEnvironment69 }
     * 
     */
    public CardPaymentEnvironment69 createCardPaymentEnvironment69() {
        return new CardPaymentEnvironment69();
    }

    /**
     * Create an instance of {@link PaymentCard28 }
     * 
     */
    public PaymentCard28 createPaymentCard28() {
        return new PaymentCard28();
    }

    /**
     * Create an instance of {@link TMSTrigger1 }
     * 
     */
    public TMSTrigger1 createTMSTrigger1() {
        return new TMSTrigger1();
    }

    /**
     * Create an instance of {@link GenericIdentification32 }
     * 
     */
    public GenericIdentification32 createGenericIdentification32() {
        return new GenericIdentification32();
    }

    /**
     * Create an instance of {@link ActionMessage2 }
     * 
     */
    public ActionMessage2 createActionMessage2() {
        return new ActionMessage2();
    }

    /**
     * Create an instance of {@link Action8 }
     * 
     */
    public Action8 createAction8() {
        return new Action8();
    }

    /**
     * Create an instance of {@link TransactionIdentifier1 }
     * 
     */
    public TransactionIdentifier1 createTransactionIdentifier1() {
        return new TransactionIdentifier1();
    }

    /**
     * Create an instance of {@link Parameter12 }
     * 
     */
    public Parameter12 createParameter12() {
        return new Parameter12();
    }

    /**
     * Create an instance of {@link Parameter10 }
     * 
     */
    public Parameter10 createParameter10() {
        return new Parameter10();
    }

    /**
     * Create an instance of {@link EnvelopedData5 }
     * 
     */
    public EnvelopedData5 createEnvelopedData5() {
        return new EnvelopedData5();
    }

    /**
     * Create an instance of {@link CardPaymentTransaction57 }
     * 
     */
    public CardPaymentTransaction57 createCardPaymentTransaction57() {
        return new CardPaymentTransaction57();
    }

    /**
     * Create an instance of {@link EncryptedContent4 }
     * 
     */
    public EncryptedContent4 createEncryptedContent4() {
        return new EncryptedContent4();
    }

    /**
     * Create an instance of {@link AuthorisationResult12 }
     * 
     */
    public AuthorisationResult12 createAuthorisationResult12() {
        return new AuthorisationResult12();
    }

    /**
     * Create an instance of {@link GenericIdentification94 }
     * 
     */
    public GenericIdentification94 createGenericIdentification94() {
        return new GenericIdentification94();
    }

    /**
     * Create an instance of {@link ContentInformationType17 }
     * 
     */
    public ContentInformationType17 createContentInformationType17() {
        return new ContentInformationType17();
    }

    /**
     * Create an instance of {@link EncapsulatedContent3 }
     * 
     */
    public EncapsulatedContent3 createEncapsulatedContent3() {
        return new EncapsulatedContent3();
    }

    /**
     * Create an instance of {@link RelativeDistinguishedName1 }
     * 
     */
    public RelativeDistinguishedName1 createRelativeDistinguishedName1() {
        return new RelativeDistinguishedName1();
    }

    /**
     * Create an instance of {@link Traceability5 }
     * 
     */
    public Traceability5 createTraceability5() {
        return new Traceability5();
    }

    /**
     * Create an instance of {@link ContentInformationType16 }
     * 
     */
    public ContentInformationType16 createContentInformationType16() {
        return new ContentInformationType16();
    }

    /**
     * Create an instance of {@link CardPaymentTransaction68 }
     * 
     */
    public CardPaymentTransaction68 createCardPaymentTransaction68() {
        return new CardPaymentTransaction68();
    }

    /**
     * Create an instance of {@link ResponseType5 }
     * 
     */
    public ResponseType5 createResponseType5() {
        return new ResponseType5();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification18 }
     * 
     */
    public AlgorithmIdentification18 createAlgorithmIdentification18() {
        return new AlgorithmIdentification18();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification19 }
     * 
     */
    public AlgorithmIdentification19 createAlgorithmIdentification19() {
        return new AlgorithmIdentification19();
    }

    /**
     * Create an instance of {@link GenericIdentification90 }
     * 
     */
    public GenericIdentification90 createGenericIdentification90() {
        return new GenericIdentification90();
    }

    /**
     * Create an instance of {@link Header35 }
     * 
     */
    public Header35 createHeader35() {
        return new Header35();
    }

    /**
     * Create an instance of {@link Recipient5Choice }
     * 
     */
    public Recipient5Choice createRecipient5Choice() {
        return new Recipient5Choice();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification22 }
     * 
     */
    public AlgorithmIdentification22 createAlgorithmIdentification22() {
        return new AlgorithmIdentification22();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification23 }
     * 
     */
    public AlgorithmIdentification23 createAlgorithmIdentification23() {
        return new AlgorithmIdentification23();
    }

    /**
     * Create an instance of {@link AlgorithmIdentification24 }
     * 
     */
    public AlgorithmIdentification24 createAlgorithmIdentification24() {
        return new AlgorithmIdentification24();
    }

    /**
     * Create an instance of {@link NetworkParameters5 }
     * 
     */
    public NetworkParameters5 createNetworkParameters5() {
        return new NetworkParameters5();
    }

    /**
     * Create an instance of {@link AcceptorCancellationResponse7 }
     * 
     */
    public AcceptorCancellationResponse7 createAcceptorCancellationResponse7() {
        return new AcceptorCancellationResponse7();
    }

    /**
     * Create an instance of {@link NetworkParameters4 }
     * 
     */
    public NetworkParameters4 createNetworkParameters4() {
        return new NetworkParameters4();
    }

    /**
     * Create an instance of {@link Recipient6Choice }
     * 
     */
    public Recipient6Choice createRecipient6Choice() {
        return new Recipient6Choice();
    }

    /**
     * Create an instance of {@link GenericIdentification76 }
     * 
     */
    public GenericIdentification76 createGenericIdentification76() {
        return new GenericIdentification76();
    }

    /**
     * Create an instance of {@link IssuerAndSerialNumber1 }
     * 
     */
    public IssuerAndSerialNumber1 createIssuerAndSerialNumber1() {
        return new IssuerAndSerialNumber1();
    }

    /**
     * Create an instance of {@link OriginatorInformation1 }
     * 
     */
    public OriginatorInformation1 createOriginatorInformation1() {
        return new OriginatorInformation1();
    }

    /**
     * Create an instance of {@link CardPaymentToken4 }
     * 
     */
    public CardPaymentToken4 createCardPaymentToken4() {
        return new CardPaymentToken4();
    }

    /**
     * Create an instance of {@link AcceptorCancellationResponseV07 }
     * 
     */
    public AcceptorCancellationResponseV07 createAcceptorCancellationResponseV07() {
        return new AcceptorCancellationResponseV07();
    }

    /**
     * Create an instance of {@link Parameter7 }
     * 
     */
    public Parameter7 createParameter7() {
        return new Parameter7();
    }

    /**
     * Create an instance of {@link KEKIdentifier2 }
     * 
     */
    public KEKIdentifier2 createKEKIdentifier2() {
        return new KEKIdentifier2();
    }

    /**
     * Create an instance of {@link Parameter9 }
     * 
     */
    public Parameter9 createParameter9() {
        return new Parameter9();
    }

    /**
     * Create an instance of {@link PaymentTokenIdentifiers1 }
     * 
     */
    public PaymentTokenIdentifiers1 createPaymentTokenIdentifiers1() {
        return new PaymentTokenIdentifiers1();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:caaa.006.001.07", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
