//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.25 at 03:10:50 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:caaa.015.001.05", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.girmiti.nexo.acceptorrejection;
