//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 06:18:14 PM IST 
//


package com.girmiti.nexo.acceptorbatchtransfer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardFallback1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CardFallback1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FFLB"/>
 *     &lt;enumeration value="SFLB"/>
 *     &lt;enumeration value="NFLB"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CardFallback1Code")
@XmlEnum
public enum CardFallback1Code {

    FFLB,
    SFLB,
    NFLB;

    public String value() {
        return name();
    }

    public static CardFallback1Code fromValue(String v) {
        return valueOf(v);
    }

}
