//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 06:18:14 PM IST 
//


package com.girmiti.nexo.acceptorbatchtransfer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardPaymentDataSetTransaction7Choice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardPaymentDataSetTransaction7Choice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Cmpltn" type="{urn:iso:std:iso:20022:tech:xsd:caaa.011.001.08}CardPaymentDataSetTransaction28"/>
 *         &lt;element name="Cxl" type="{urn:iso:std:iso:20022:tech:xsd:caaa.011.001.08}CardPaymentDataSetTransaction29"/>
 *         &lt;element name="AuthstnReq" type="{urn:iso:std:iso:20022:tech:xsd:caaa.011.001.08}CardPaymentDataSetTransaction27"/>
 *         &lt;element name="AuthstnRspn" type="{urn:iso:std:iso:20022:tech:xsd:caaa.011.001.08}CardPaymentDataSetTransaction26"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardPaymentDataSetTransaction7Choice", propOrder = {
    "cmpltn",
    "cxl",
    "authstnReq",
    "authstnRspn"
})
public class CardPaymentDataSetTransaction7Choice {

    @XmlElement(name = "Cmpltn")
    protected CardPaymentDataSetTransaction28 cmpltn;
    @XmlElement(name = "Cxl")
    protected CardPaymentDataSetTransaction29 cxl;
    @XmlElement(name = "AuthstnReq")
    protected CardPaymentDataSetTransaction27 authstnReq;
    @XmlElement(name = "AuthstnRspn")
    protected CardPaymentDataSetTransaction26 authstnRspn;

    /**
     * Gets the value of the cmpltn property.
     * 
     * @return
     *     possible object is
     *     {@link CardPaymentDataSetTransaction28 }
     *     
     */
    public CardPaymentDataSetTransaction28 getCmpltn() {
        return cmpltn;
    }

    /**
     * Sets the value of the cmpltn property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardPaymentDataSetTransaction28 }
     *     
     */
    public void setCmpltn(CardPaymentDataSetTransaction28 value) {
        this.cmpltn = value;
    }

    /**
     * Gets the value of the cxl property.
     * 
     * @return
     *     possible object is
     *     {@link CardPaymentDataSetTransaction29 }
     *     
     */
    public CardPaymentDataSetTransaction29 getCxl() {
        return cxl;
    }

    /**
     * Sets the value of the cxl property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardPaymentDataSetTransaction29 }
     *     
     */
    public void setCxl(CardPaymentDataSetTransaction29 value) {
        this.cxl = value;
    }

    /**
     * Gets the value of the authstnReq property.
     * 
     * @return
     *     possible object is
     *     {@link CardPaymentDataSetTransaction27 }
     *     
     */
    public CardPaymentDataSetTransaction27 getAuthstnReq() {
        return authstnReq;
    }

    /**
     * Sets the value of the authstnReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardPaymentDataSetTransaction27 }
     *     
     */
    public void setAuthstnReq(CardPaymentDataSetTransaction27 value) {
        this.authstnReq = value;
    }

    /**
     * Gets the value of the authstnRspn property.
     * 
     * @return
     *     possible object is
     *     {@link CardPaymentDataSetTransaction26 }
     *     
     */
    public CardPaymentDataSetTransaction26 getAuthstnRspn() {
        return authstnRspn;
    }

    /**
     * Sets the value of the authstnRspn property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardPaymentDataSetTransaction26 }
     *     
     */
    public void setAuthstnRspn(CardPaymentDataSetTransaction26 value) {
        this.authstnRspn = value;
    }

}
