//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 06:18:14 PM IST 
//


package com.girmiti.nexo.acceptorbatchtransfer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POIComponentType5Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="POIComponentType5Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AQPP"/>
 *     &lt;enumeration value="APPR"/>
 *     &lt;enumeration value="TLPR"/>
 *     &lt;enumeration value="SCPR"/>
 *     &lt;enumeration value="SERV"/>
 *     &lt;enumeration value="TERM"/>
 *     &lt;enumeration value="DVCE"/>
 *     &lt;enumeration value="SECM"/>
 *     &lt;enumeration value="APLI"/>
 *     &lt;enumeration value="EMVK"/>
 *     &lt;enumeration value="EMVO"/>
 *     &lt;enumeration value="MDWR"/>
 *     &lt;enumeration value="DRVR"/>
 *     &lt;enumeration value="OPST"/>
 *     &lt;enumeration value="MRPR"/>
 *     &lt;enumeration value="CRTF"/>
 *     &lt;enumeration value="TMSP"/>
 *     &lt;enumeration value="SACP"/>
 *     &lt;enumeration value="SAPR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "POIComponentType5Code")
@XmlEnum
public enum POIComponentType5Code {

    AQPP,
    APPR,
    TLPR,
    SCPR,
    SERV,
    TERM,
    DVCE,
    SECM,
    APLI,
    EMVK,
    EMVO,
    MDWR,
    DRVR,
    OPST,
    MRPR,
    CRTF,
    TMSP,
    SACP,
    SAPR;

    public String value() {
        return name();
    }

    public static POIComponentType5Code fromValue(String v) {
        return valueOf(v);
    }

}
