//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 05:40:01 PM IST 
//


package com.girmiti.nexo.acceptorcurrencyconversionadvice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OnLineReason1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OnLineReason1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RNDM"/>
 *     &lt;enumeration value="ICCF"/>
 *     &lt;enumeration value="MERF"/>
 *     &lt;enumeration value="TRMF"/>
 *     &lt;enumeration value="ISSF"/>
 *     &lt;enumeration value="FRLT"/>
 *     &lt;enumeration value="EXFL"/>
 *     &lt;enumeration value="TAMT"/>
 *     &lt;enumeration value="CBIN"/>
 *     &lt;enumeration value="UBIN"/>
 *     &lt;enumeration value="CPAN"/>
 *     &lt;enumeration value="FLOW"/>
 *     &lt;enumeration value="CRCY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OnLineReason1Code")
@XmlEnum
public enum OnLineReason1Code {

    RNDM,
    ICCF,
    MERF,
    TRMF,
    ISSF,
    FRLT,
    EXFL,
    TAMT,
    CBIN,
    UBIN,
    CPAN,
    FLOW,
    CRCY;

    public String value() {
        return name();
    }

    public static OnLineReason1Code fromValue(String v) {
        return valueOf(v);
    }

}
