//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.19 at 03:50:05 PM IST 
//


package com.girmiti.nexo.acceptorcompletionadvice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardPaymentServiceType12Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CardPaymentServiceType12Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BALC"/>
 *     &lt;enumeration value="CACT"/>
 *     &lt;enumeration value="CRDP"/>
 *     &lt;enumeration value="CAFH"/>
 *     &lt;enumeration value="CAVR"/>
 *     &lt;enumeration value="CSHW"/>
 *     &lt;enumeration value="CSHD"/>
 *     &lt;enumeration value="DEFR"/>
 *     &lt;enumeration value="LOAD"/>
 *     &lt;enumeration value="ORCR"/>
 *     &lt;enumeration value="PINC"/>
 *     &lt;enumeration value="QUCH"/>
 *     &lt;enumeration value="RFND"/>
 *     &lt;enumeration value="RESA"/>
 *     &lt;enumeration value="VALC"/>
 *     &lt;enumeration value="UNLD"/>
 *     &lt;enumeration value="CAFT"/>
 *     &lt;enumeration value="CAFL"/>
 *     &lt;enumeration value="CIDD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CardPaymentServiceType12Code")
@XmlEnum
public enum CardPaymentServiceType12Code {

    BALC,
    CACT,
    CRDP,
    CAFH,
    CAVR,
    CSHW,
    CSHD,
    DEFR,
    LOAD,
    ORCR,
    PINC,
    QUCH,
    RFND,
    RESA,
    VALC,
    UNLD,
    CAFT,
    CAFL,
    CIDD;

    public String value() {
        return name();
    }

    public static CardPaymentServiceType12Code fromValue(String v) {
        return valueOf(v);
    }

}
