//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.26 at 12:11:06 PM IST 
//


package com.girmiti.nexo.acceptordiagnosticresponse;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POICommunicationType2Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="POICommunicationType2Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BLTH"/>
 *     &lt;enumeration value="ETHR"/>
 *     &lt;enumeration value="GPRS"/>
 *     &lt;enumeration value="GSMF"/>
 *     &lt;enumeration value="PSTN"/>
 *     &lt;enumeration value="RS23"/>
 *     &lt;enumeration value="USBD"/>
 *     &lt;enumeration value="USBH"/>
 *     &lt;enumeration value="WIFI"/>
 *     &lt;enumeration value="WT2G"/>
 *     &lt;enumeration value="WT3G"/>
 *     &lt;enumeration value="WT4G"/>
 *     &lt;enumeration value="WT5G"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "POICommunicationType2Code")
@XmlEnum
public enum POICommunicationType2Code {

    BLTH("BLTH"),
    ETHR("ETHR"),
    GPRS("GPRS"),
    GSMF("GSMF"),
    PSTN("PSTN"),
    @XmlEnumValue("RS23")
    RS_23("RS23"),
    USBD("USBD"),
    USBH("USBH"),
    WIFI("WIFI"),
    @XmlEnumValue("WT2G")
    WT_2_G("WT2G"),
    @XmlEnumValue("WT3G")
    WT_3_G("WT3G"),
    @XmlEnumValue("WT4G")
    WT_4_G("WT4G"),
    @XmlEnumValue("WT5G")
    WT_5_G("WT5G");
    private final String value;

    POICommunicationType2Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static POICommunicationType2Code fromValue(String v) {
        for (POICommunicationType2Code c: POICommunicationType2Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
