//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.25 at 03:53:54 PM IST 
//


package com.girmiti.nexo.acceptorbatchtransferresponse;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Algorithm18Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Algorithm18Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EA2C"/>
 *     &lt;enumeration value="E3DC"/>
 *     &lt;enumeration value="DKP9"/>
 *     &lt;enumeration value="UKPT"/>
 *     &lt;enumeration value="UKA1"/>
 *     &lt;enumeration value="EA9C"/>
 *     &lt;enumeration value="EA5C"/>
 *     &lt;enumeration value="DA12"/>
 *     &lt;enumeration value="DA19"/>
 *     &lt;enumeration value="DA25"/>
 *     &lt;enumeration value="N108"/>
 *     &lt;enumeration value="EA5R"/>
 *     &lt;enumeration value="EA9R"/>
 *     &lt;enumeration value="EA2R"/>
 *     &lt;enumeration value="E3DR"/>
 *     &lt;enumeration value="E36C"/>
 *     &lt;enumeration value="E36R"/>
 *     &lt;enumeration value="SD5C"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Algorithm18Code")
@XmlEnum
public enum Algorithm18Code {

    @XmlEnumValue("EA2C")
    EA_2_C("EA2C"),
    @XmlEnumValue("E3DC")
    E_3_DC("E3DC"),
    @XmlEnumValue("DKP9")
    DKP_9("DKP9"),
    UKPT("UKPT"),
    @XmlEnumValue("UKA1")
    UKA_1("UKA1"),
    @XmlEnumValue("EA9C")
    EA_9_C("EA9C"),
    @XmlEnumValue("EA5C")
    EA_5_C("EA5C"),
    @XmlEnumValue("DA12")
    DA_12("DA12"),
    @XmlEnumValue("DA19")
    DA_19("DA19"),
    @XmlEnumValue("DA25")
    DA_25("DA25"),
    @XmlEnumValue("N108")
    N_108("N108"),
    @XmlEnumValue("EA5R")
    EA_5_R("EA5R"),
    @XmlEnumValue("EA9R")
    EA_9_R("EA9R"),
    @XmlEnumValue("EA2R")
    EA_2_R("EA2R"),
    @XmlEnumValue("E3DR")
    E_3_DR("E3DR"),
    @XmlEnumValue("E36C")
    E_36_C("E36C"),
    @XmlEnumValue("E36R")
    E_36_R("E36R"),
    @XmlEnumValue("SD5C")
    SD_5_C("SD5C");
    private final String value;

    Algorithm18Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Algorithm18Code fromValue(String v) {
        for (Algorithm18Code c: Algorithm18Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
