//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.25 at 04:35:07 AM PDT 
//


package com.girmiti.nexo.acceptorreconciliationreqest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeTransactionTotals2Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeTransactionTotals2Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CRDT"/>
 *     &lt;enumeration value="CRDR"/>
 *     &lt;enumeration value="DEBT"/>
 *     &lt;enumeration value="DBTR"/>
 *     &lt;enumeration value="DECL"/>
 *     &lt;enumeration value="FAIL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeTransactionTotals2Code")
@XmlEnum
public enum TypeTransactionTotals2Code {

    CRDT,
    CRDR,
    DEBT,
    DBTR,
    DECL,
    FAIL;

    public String value() {
        return name();
    }

    public static TypeTransactionTotals2Code fromValue(String v) {
        return valueOf(v);
    }

}
