//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.19 at 12:37:53 PM IST 
//


package com.girmiti.nexo.acceptorauthorizationrequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressVerification1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressVerification1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AdrDgts" type="{urn:iso:std:iso:20022:tech:xsd:caaa.001.001.08}Max5NumericText" minOccurs="0"/>
 *         &lt;element name="PstlCdDgts" type="{urn:iso:std:iso:20022:tech:xsd:caaa.001.001.08}Max5NumericText" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressVerification1", propOrder = {
    "adrDgts",
    "pstlCdDgts"
})
public class AddressVerification1 {

    @XmlElement(name = "AdrDgts")
    protected String adrDgts;
    @XmlElement(name = "PstlCdDgts")
    protected String pstlCdDgts;

    /**
     * Gets the value of the adrDgts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdrDgts() {
        return adrDgts;
    }

    /**
     * Sets the value of the adrDgts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdrDgts(String value) {
        this.adrDgts = value;
    }

    /**
     * Gets the value of the pstlCdDgts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPstlCdDgts() {
        return pstlCdDgts;
    }

    /**
     * Sets the value of the pstlCdDgts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPstlCdDgts(String value) {
        this.pstlCdDgts = value;
    }

}
