//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.19 at 12:37:53 PM IST 
//


package com.girmiti.nexo.acceptorauthorizationrequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthenticationEntity2Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AuthenticationEntity2Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ICCD"/>
 *     &lt;enumeration value="AGNT"/>
 *     &lt;enumeration value="MERC"/>
 *     &lt;enumeration value="ACQR"/>
 *     &lt;enumeration value="ISSR"/>
 *     &lt;enumeration value="TRML"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AuthenticationEntity2Code")
@XmlEnum
public enum AuthenticationEntity2Code {

    ICCD,
    AGNT,
    MERC,
    ACQR,
    ISSR,
    TRML;

    public String value() {
        return name();
    }

    public static AuthenticationEntity2Code fromValue(String v) {
        return valueOf(v);
    }

}
