//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.19 at 12:37:53 PM IST 
//


package com.girmiti.nexo.acceptorauthorizationrequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionChannel5Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransactionChannel5Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MAIL"/>
 *     &lt;enumeration value="TLPH"/>
 *     &lt;enumeration value="ECOM"/>
 *     &lt;enumeration value="TVPY"/>
 *     &lt;enumeration value="SECM"/>
 *     &lt;enumeration value="MOBL"/>
 *     &lt;enumeration value="MPOS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransactionChannel5Code")
@XmlEnum
public enum TransactionChannel5Code {

    MAIL,
    TLPH,
    ECOM,
    TVPY,
    SECM,
    MOBL,
    MPOS;

    public String value() {
        return name();
    }

    public static TransactionChannel5Code fromValue(String v) {
        return valueOf(v);
    }

}
