//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.19 at 12:37:53 PM IST 
//


package com.girmiti.nexo.acceptorauthorizationrequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Verification1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Verification1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FAIL"/>
 *     &lt;enumeration value="MISS"/>
 *     &lt;enumeration value="NOVF"/>
 *     &lt;enumeration value="PART"/>
 *     &lt;enumeration value="SUCC"/>
 *     &lt;enumeration value="ERRR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Verification1Code")
@XmlEnum
public enum Verification1Code {

    FAIL,
    MISS,
    NOVF,
    PART,
    SUCC,
    ERRR;

    public String value() {
        return name();
    }

    public static Verification1Code fromValue(String v) {
        return valueOf(v);
    }

}
