//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 06:14:38 PM IST 
//


package com.girmiti.nexo.acceptorcancellationreqest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthenticationMethod6Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AuthenticationMethod6Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NPIN"/>
 *     &lt;enumeration value="PPSG"/>
 *     &lt;enumeration value="PSWD"/>
 *     &lt;enumeration value="SCRT"/>
 *     &lt;enumeration value="SCNL"/>
 *     &lt;enumeration value="SNCT"/>
 *     &lt;enumeration value="CPSG"/>
 *     &lt;enumeration value="ADDB"/>
 *     &lt;enumeration value="BIOM"/>
 *     &lt;enumeration value="CDHI"/>
 *     &lt;enumeration value="CRYP"/>
 *     &lt;enumeration value="CSCV"/>
 *     &lt;enumeration value="PSVE"/>
 *     &lt;enumeration value="CSEC"/>
 *     &lt;enumeration value="ADDS"/>
 *     &lt;enumeration value="MANU"/>
 *     &lt;enumeration value="FPIN"/>
 *     &lt;enumeration value="TOKP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AuthenticationMethod6Code")
@XmlEnum
public enum AuthenticationMethod6Code {

    NPIN,
    PPSG,
    PSWD,
    SCRT,
    SCNL,
    SNCT,
    CPSG,
    ADDB,
    BIOM,
    CDHI,
    CRYP,
    CSCV,
    PSVE,
    CSEC,
    ADDS,
    MANU,
    FPIN,
    TOKP;

    public String value() {
        return name();
    }

    public static AuthenticationMethod6Code fromValue(String v) {
        return valueOf(v);
    }

}
